# Generated by Django 5.1.4 on 2025-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'สำเนาบัตรประชาชน'), ('house_registration', 'สำเนาทะเบียนบ้าน'), ('violator_id_card', 'บัตรประชาชนผู้กระทำ'), ('violator_house_registration', 'ทะเบียนบ้านผู้กระทำ'), ('injury_evidence', 'หลักฐานการบาดเจ็บ')], max_length=255, verbose_name='ประเภทเอกสาร')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='ไฟล์รูปภาพ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่อัปโหลด')),
            ],
        ),
    ]
